src/Entity/Question.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\QuestionRepository")
 * @Vich\Uploadable
 */
class Question
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $query;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $answerA;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $answerB;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $answerC;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $answerD;

    /**
     * @ORM\Column(type="smallint")
     * @Assert\Range(
     *      min = 1,
     *      max = 4,
     *      minMessage = "You must enter [1, 2, 3, 4] values",
     *      maxMessage = "You must enter [1, 2, 3, 4] values"
     * )
     */
    private $correct;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(
     *      max = 255,
     *      maxMessage = "Image name cannot be longer than {{ limit }} characters"
     * )
     */
    private $imageName;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank()
     * @Assert\DateTime
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Qualification", inversedBy="questions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $qualification;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\DateTime
     */
    private $updatedAt;
	
	/**
     * @var integer
     */
    private $user_answer;
	
	/**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="exam_question_directory", fileNameProperty="imageName")
     * @Assert\File()
     * @Assert\Image(
     *   mimeTypes = {
     *     "image/png",
     *     "image/jpeg",
     *     "image/jpg"
     *   },
     *   mimeTypesMessage = "Invalid mime type. Allowed types [png, jpeg, jpg]"
     * )
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     * @Assert\Length(
     *      max = 20,
     *      maxMessage = "Session name cannot be longer than {{ limit }} characters"
     * )
     */
    private $session;

    /**
     * @ORM\Column(type="string", length=4, nullable=true)
     * @Assert\Length(
     *      max = 4,
     *      maxMessage = "Year cannot be longer than {{ limit }} characters"
     * )
     */
    private $year;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $external_id;

    public function __construct()
    {
        $now = new \DateTime('now');
        $this->createdAt = $now;
        $this->updatedAt = $now;
    }

    public function getId(): ?int
    {
        return $this->id;
    }
	
	/**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }
	
	public function setUserAnswer(int $user_answer) : self
                                        {
                                            $this->user_answer = $user_answer;
                                    
                                            return $this;
                                        }

    public function getUserAnswer() : int
    {
        return $this->user_answer;
    }

    public function getQuery(): ?string
    {
        return $this->query;
    }

    public function setQuery(string $query): self
    {
        $this->query = $query;

        return $this;
    }

    public function getAnswerA(): ?string
    {
        return $this->answerA;
    }

    public function setAnswerA(string $answerA): self
    {
        $this->answerA = $answerA;

        return $this;
    }

    public function getAnswerB(): ?string
    {
        return $this->answerB;
    }

    public function setAnswerB(string $answerB): self
    {
        $this->answerB = $answerB;

        return $this;
    }

    public function getAnswerC(): ?string
    {
        return $this->answerC;
    }

    public function setAnswerC(string $answerC): self
    {
        $this->answerC = $answerC;

        return $this;
    }

    public function getAnswerD(): ?string
    {
        return $this->answerD;
    }

    public function setAnswerD(string $answerD): self
    {
        $this->answerD = $answerD;

        return $this;
    }

    public function getCorrect(): ?int
    {
        return $this->correct;
    }

    public function setCorrect(int $correct): self
    {
        $this->correct = $correct;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getQualification(): ?Qualification
    {
        return $this->qualification;
    }

    public function setQualification(?Qualification $qualification): self
    {
        $this->qualification = $qualification;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getSession(): ?string
    {
        return $this->session;
    }

    public function setSession(?string $session): self
    {
        $this->session = $session;

        return $this;
    }

    public function getYear(): ?string
    {
        return $this->year;
    }

    public function setYear(?string $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getExternalId(): ?int
    {
        return $this->external_id;
    }

    public function setExternalId(?int $external_id): self
    {
        $this->external_id = $external_id;

        return $this;
    }
}

src/Controller/ExamController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Exam\Exam;
use App\Exam\ExamValidator;
use App\Entity\Question;
use App\Entity\Qualification;
use App\Service\QualificationGenerator;

class ExamController extends AbstractController
{
    /**
     * @Route("/egzamin-zawodowy/generator/{stage_id}-{friendly_stage_url}", name="redirect_exam")
     */
    public function selectQualificationsFormRedirection(Request $request, QualificationGenerator $qualificationGenerator, $friendly_stage_url, $stage_id)
    {
        $qualification_id = $request->get('qualification_id');
        $question_quantity = $request->get('question_quantity');

        if (empty($qualification_id) || empty($question_quantity)) {
            $this->redirectToRoute('homepage', null, 302);
        }
        
        $friendly_qualification_url = $qualificationGenerator->get($qualification_id)->getFriendlyUrl();;

        return $this->redirectToRoute('generate_exam', [
            'qualification_id'   =>  $qualification_id,
            'question_quantity'  =>  $question_quantity,
            'friendly_stage_url' =>  $friendly_stage_url,
            'friendly_qualification_url' => $friendly_qualification_url,
            'stage_id'  =>  $stage_id
        ], 302);
    }

    /**
     * @Route("/egzamin-zawodowy/{question_quantity}/{stage_id}/{qualification_id}/{friendly_stage_url}/{friendly_qualification_url}", name="generate_exam")
     */
    public function generateExam(Request $request, $qualification_id, $stage_id, $question_quantity, $friendly_qualification_url, $friendly_stage_url)
    {
        if (empty($qualification_id) || empty($question_quantity) || empty($stage_id) || !is_numeric($question_quantity) || !is_numeric($qualification_id) || !is_numeric($stage_id)) {
            return $this->redirectToRoute('home_page', [], 302);
        }

        if (!ExamValidator::isCorrectNumberOfQuestions($question_quantity)) {
            return $this->redirectToRoute('home_page', [], 302);
        }
        
        $em = $this->getDoctrine()->getManager();
        $qualification = $em->getRepository(Qualification::class)->find($qualification_id);
        $questions = $em->getRepository(Question::class)
                        ->getRandomEntities($qualification_id, $question_quantity);
                    
        $exam = new Exam($questions);

        if (empty($questions)) {
            return $this->redirectToRoute('home_page', [], 302);
        }

        $request->getSession()->set('exam', $exam);
        $request->getSession()->set('qualification_id', $qualification_id);
        $request->getSession()->set('qualification_designation', $qualification->getDesignation());
        $request->getSession()->set('qualification_meta_desc', $qualification->getMetaDescription());
        $request->getSession()->set('friendly_stage_url', $friendly_stage_url);
        $request->getSession()->set('friendly_qualification_url', $qualification->getFriendlyUrl());
        $stage_name = ucfirst(str_replace('-', ' ', $friendly_stage_url));
        $request->getSession()->set('stage_name', $stage_name);
        $request->getSession()->set('stage_id', $stage_id);

        return $this->render('exam/show.html.twig', [
            'questions'  => $questions,
            'qualification'    =>  $qualification,
            'question_quantity'    =>  $question_quantity,
            'stage_name'    =>  $stage_name,
            'stage_id' => $stage_id,
            'friendly_stage_url' => $friendly_stage_url
        ]);
    }

    /**
     * @Route("/egzamin-zawodowy/{friendly_stage}/podsumowanie", name="check_exam")
     */
    public function checkExam(Request $request)
    {
        $exam = $request->getSession()->get('exam');

        if (empty($exam)) {
            return $this->redirectToRoute('home_page');
        }

        $stage_id = $request->getSession()->get('stage_id');
        $friendly_qualification_url = $request->getSession()->get('friendly_qualification_url');
        $friendly_stage_url = $request->getSession()->get('friendly_stage_url');
        $qualification_id = $request->getSession()->get('qualification_id');
        $stage_name = $request->getSession()->get('stage_name');
        $qualification_designation = $request->getSession()->get('qualification_designation');
        $qualification_meta_desc = $request->getSession()->get('qualification_meta_desc');

        $answers = $request->request->all();
        $exam->setAnswers($answers['answers'])
            ->checkQuestions();

        $request->getSession()->clear();
        
        return $this->render('exam/summary.html.twig', [
            'questions'         => $exam->getQuestions(),
            'points'            => $exam->getPoints(),
            'percent'           => $exam->getPercent(),
            'question_quantity' => $exam->getQuestionQuantity(),
            'stage_id'  => $stage_id,
            'friendly_qualification_url' => $friendly_qualification_url,
            'friendly_stage_url' => $friendly_stage_url,
            'qualification_id' => $qualification_id,
            'stage_name' => $stage_name,
            'qualification_designation' =>  $qualification_designation,
            'qualification_meta_desc' => $qualification_meta_desc
        ]);
    }
}

templates/exam/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ stage_name }} - Kwalifikacja {{ qualification.designation }}{% endblock %} 
{% block metaDescription %}Wylosuj {{ question_quantity }} pytań. {{ qualification.metaDescription }}{% endblock %} 

{% block stylesheets %} 
    {{ parent() }}

    <link rel="stylesheet" type="text/css" href="{{ asset('css/checkboxes.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/page-layout-helpers.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/universal.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/exam.css') }}"> 
{% endblock %} 

{% block body %}

    {# ------ Breadcrumb -------- #}
    <nav id="breadcrumb-nav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item" itemscope itemtype="https://data-vocabulary.org/Breadcrumb">
                <a href="{{ path('home_page') }}" itemprop="url">
                    <span itemprop="title">Strona główna</span>
                </a>
            </li>

            <li class="breadcrumb-item" itemscope itemtype="https://data-vocabulary.org/Breadcrumb">
                <a href="{{ path('stage', {'id': stage_id, 'friendly_url': friendly_stage_url}) }}" itemprop="url">
                    <span itemprop="title">{{ stage_name }}</span>
                </a>
            </li>

            <li class="breadcrumb-item active" itemscope itemtype="https://data-vocabulary.org/Breadcrumb">
                <span itemprop="title">Kwalifikacja {{ qualification.designation }}</span>
                <meta itemprop="url" content="{{ url(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')) }}">
            </li>
        </ol>
    </nav>
    {# ------ End breadcrumb -------- #}

    <section class="qualification-title-container">
        <h1 class="qualification-title left-white-space">Kwalifikacja {{ qualification.designation }} - {{ qualification.description }}</h1>
    </section>

    <form id="exam-form" method="POST" action="{{ path('check_exam', {'friendly_stage': friendly_stage_url}) }}">
        <div class="left-white-space">
            <div style="margin-top: 5px">Kliknięcie spowoduje pokazanie pytania.</div>
            <div id="questions-panel">
                {% for question in questions %} 
                    {% if loop.index0 % 2 == 0 %}
                        <div class="column">
                    {% endif %}
                        <div data-question-number="{{ loop.index0 }}" data-is-filled="false" class="square {% if loop.index0 == 0 %} square-active{% else %} square-empty{% endif %}"></div>
                    {% if (loop.index % 2 == 0 and loop.index != 0) %}
                        </div>
                    {% endif %} 
                {% endfor %} 
                {% if questions|length % 2 == 1 %}
                        </div>
                {% endif %}
                <p id="quick-view"></p>
                <div class="floating-cleaner"></div>
            </div>

            <div id="question-group-container">
                {% for question in questions %}
                    <section class="question-group" {% if loop.index==1 %} style="display:block" {% endif %}>
                        <p class="text-faded text-before-devider">pytanie {{ loop.index }} z {{ question_quantity }}</p>
                        <div class="devider exam-devider"></div>

                        <h2 style="font-size: 18px;">{{ loop.index }}. <span class="query">{{ question.query|e('html')|raw }}</span></h2>
                        
                        <div class="row">
                            <div class="answers-group col-lg-{% if question.imageName %}6{% else %}12{% endif %}" data-question-number="{{ loop.index0 }}">
                                <input type="hidden" class="user_answer" name="answers[{{ loop.index0 }}]">

                                <div class="column question-panel-margin">
                                    <div class="checkbox-group answer" data-value="1">
                                        <div class="checkbox"></div>
                                        <div class="checkbox-label">{{ question.answerA|e('html')|raw }}</div>
                                    </div>
                                    <div class="checkbox-group answer" data-value="2">
                                        <div class="checkbox"></div>
                                        <div class="checkbox-label">{{ question.answerB|e('html')|raw }}</div>
                                    </div>
                                </div>
                                <div class="column">
                                    <div class="checkbox-group answer" data-value="3">
                                        <div class="checkbox"></div>
                                        <div class="checkbox-label">{{ question.answerC|e('html')|raw }}</div>
                                    </div>
                                    <div class="checkbox-group answer" data-value="4">
                                        <div class="checkbox"></div>
                                        <div class="checkbox-label">{{ question.answerD|e('html')|raw }}</div>
                                    </div>
                                </div>
                            </div>

                            {% if question.imageName %}
                                <div class="col-lg-6">
                                    <img class="img-fluid" style="margin-top:15px;" src="{{ asset('uploads/exams/'~question.imageName) }}" alt="Nie udało się załadować zdjęcia">
                                </div>
                            {% endif %}
                        </div>
                    </section>
                {% endfor %}
                <div class="floating-cleaner"></div>
            </div>
        </div>

        <div id="errors-container" class="left-white-space"></div>

        <div class="bottom-btn-container">
            <div id="next-question" class="btn-nav center-btn">Następne pytanie</div>
            <input type="submit" class="btn-nav right-btn" value="Sprawdź test">
        </div>
    </form>
{% endblock %} 

{% block javascripts %} 
    {{ parent() }}

    <script src="{{ asset('js/exam.js') }}"></script>
{% endblock %}

templates/exam/summary.html.twig
{% extends 'base.html.twig' %} 

{% block title %}{{ stage_name }} - Kwalifikacja {{ qualification_designation }} / Podsumowanie{% endblock %} 
{% block metaDescription %}{{ qualification_meta_desc }}{% endblock %} 

{% block stylesheets %} 
    {{ parent() }}

    <link rel="stylesheet" type="text/css" href="{{ asset('css/checkboxes.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/page-layout-helpers.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/universal.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/exam.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('css/summary-exam.css') }}"> 
{% endblock %} 

{% block body %}

    {# ------ Breadcrumb -------- #}
    <nav id="breadcrumb-nav">
        <ol class="breadcrumb">
            <li class="breadcrumb-item" itemscope itemtype="https://data-vocabulary.org/Breadcrumb">
                <a href="{{ path('home_page') }}" itemprop="url">
                    <span itemprop="title">Strona główna</span>
                </a>
            </li>

            <li class="breadcrumb-item" itemscope itemtype="https://data-vocabulary.org/Breadcrumb">
                <a href="{{ path('stage', {'id': stage_id, 'friendly_url': friendly_stage_url}) }}" itemprop="url">
                    <span itemprop="title">{{ stage_name }}</span>
                </a>
            </li>

            <li class="breadcrumb-item active" itemscope itemtype="https://data-vocabulary.org/Breadcrumb">
                <span itemprop="title">Kwalifikacja {{ qualification.designation }} - Podsumowanie</span>
                <meta itemprop="url" content="{{ url(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')) }}">
            </li>
        </ol>
    </nav>
    {# ------ End breadcrumb -------- #}

    <section class="qualification-title-container">
        <h1 class="qualification-title left-white-space">twój wynik testu</h1>
    </section>

    <div class="left-white-space">
        <div style="margin-top: 5px">Kliknięcie spowoduje pokazanie pytania.</div>
        <div id="questions-panel">
            {% for question in questions %} 
                {% if loop.index0 % 2 == 0 %}
                    <div class="column">
                {% endif %}
                        <div data-question-number="{{ loop.index0 }}" class="square {% if question.userAnswer != question.correct %}square-false{% else %}square-correct{% endif %}"></div>
                {% if (loop.index % 2 == 0 and loop.index != 0) %}
                    </div>
                {% endif %} 
            {% endfor %} 
            
            {% if questions|length % 2 == 1 %}
                </div>
            {% endif %}
            <p id="quick-view"></p>
            <div class="floating-cleaner"></div>
        </div>
    </div>

    <div class="left-white-space" id="question-group-container">
        {% for question in questions %}
            <section class="question-group">
                <p class="text-faded text-before-devider">pytanie {{ loop.index }} z {{ question_quantity }}</p>
                <div class="devider summary-devider"></div>
                <h2 style="font-size: 18px;">{{ loop.index }}. <span class="query">{{ question.query|e('html')|raw }}</span></h2>

                <div class="row">
                    <div class="col-lg-{% if question.imageName %}6{% else %}12{% endif %}">
                        <div data-question-number="{{ loop.index0 }}" class="answers-group">
                            <div class="column question-panel-margin">
                                <div class="checkbox-group answer {% if question.correct == 1 %}checkbox-correct{% elseif question.userAnswer == 1 %}checkbox-false{% else %} {% set neutral = true %} {% endif %}">
                                    {% if (neutral is defined) and (neutral == true) %}
                                        <div class="checkbox"></div>
                                    {% set neutral = false %} {% endif %}
                                    <label class="checkbox-label">{{ question.answerA|e('html')|raw }}</label>
                                </div>
                                <div class="checkbox-group answer {% if question.correct == 2 %}checkbox-correct{% elseif question.userAnswer == 2 %}checkbox-false{% else %} {% set neutral = true %}{% endif %}">
                                    {% if (neutral is defined) and (neutral == true) %}
                                        <div class="checkbox"></div>
                                    {% set neutral = false %} {% endif %}
                                    <label class="checkbox-label">{{ question.answerB|e('html')|raw }}</label>
                                </div>
                            </div>

                            <div class="column">
                                <div class="checkbox-group answer {% if question.correct == 3 %}checkbox-correct{% elseif question.userAnswer == 3 %}checkbox-false{% else %} {% set neutral = true %}{% endif %}">
                                    {% if (neutral is defined) and (neutral == true) %}
                                        <div class="checkbox"></div>
                                    {% set neutral = false %} {% endif %}
                                    <label class="checkbox-label">{{ question.answerC|e('html')|raw }}</label>
                                </div>
                                <div class="checkbox-group answer {% if question.correct == 4 %}checkbox-correct{% elseif question.userAnswer == 4 %}checkbox-false{% else %} {% set neutral = true %}{% endif %}">
                                    {% if (neutral is defined) and (neutral == true) %}
                                        <div class="checkbox"></div>
                                    {% set neutral = false %} {% endif %}
                                    <label class="checkbox-label">{{ question.answerD|e('html')|raw }}</label>
                                </div>
                            </div>
                        </div>
                    </div>

                    {% if question.imageName %}
                        <div class="col-lg-6">
                            <img class="img-fluid" style="margin-top:15px;" src="{{ asset('uploads/exams/'~question.imageName) }}" alt="Nie udało się załadować zdjęcia">
                        </div>
                    {% endif %}
                </div>
            </section>
        {% endfor %}
        <div class="floating-cleaner"></div>

        <section>
            <p class="text-faded text-before-devider">sprawdź udzielone przez Ciebie odpowiedzi klikając w odpowiednie kratki</p>
            <div class="devider summary-devider"></div>
            
            <div class="summary-info">
                <h3 class="summary-header">Ilość poprawnych odpowiedzi: {{ points }}</h3>
                <h3 class="summary-header">Ilość złych odpowiedzi: {{ question_quantity - points }} </h3>
                <div class="exam-percent-container">
                    <h3 class="summary-header">Wynik:</h3>
                    <p class="percent-label">{{ percent }} %</p>
                </div>
            </div>
        </section>
    </div>

    <div class="bottom-btn-container">
        <a href="{{ path('generate_exam', {'stage_id': stage_id, 'question_quantity': question_quantity, 'friendly_stage_url': friendly_stage_url, 'qualification_id': qualification_id, 'friendly_qualification_url': friendly_qualification_url}) }}" class="btn-nav center-btn">Wylosuj kolejny test</a>
    </div>
{% endblock %} 

{% block javascripts %} 
    {{ parent() }}
    <script src="{{ asset('js/exam-summary.js') }}"></script>

{% endblock %}